// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBzCThWK8nHtGU03t8n22pXbDQflWmuN1w',
    appId: '1:779310827551:web:f9df1eee432308b6caed2a',
    messagingSenderId: '779310827551',
    projectId: 'inventory-app-1bd22',
    authDomain: 'inventory-app-1bd22.firebaseapp.com',
    storageBucket: 'inventory-app-1bd22.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDLjJ7coGfpzhanbBgjlgwP8Zz5jyZW-bk',
    appId: '1:779310827551:ios:3c6173c80a4bf38ecaed2a',
    messagingSenderId: '779310827551',
    projectId: 'inventory-app-1bd22',
    storageBucket: 'inventory-app-1bd22.firebasestorage.app',
    iosBundleId: 'com.example.inventoryApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDLjJ7coGfpzhanbBgjlgwP8Zz5jyZW-bk',
    appId: '1:779310827551:ios:3c6173c80a4bf38ecaed2a',
    messagingSenderId: '779310827551',
    projectId: 'inventory-app-1bd22',
    storageBucket: 'inventory-app-1bd22.firebasestorage.app',
    iosBundleId: 'com.example.inventoryApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBzCThWK8nHtGU03t8n22pXbDQflWmuN1w',
    appId: '1:779310827551:web:8f67727ff255bc41caed2a',
    messagingSenderId: '779310827551',
    projectId: 'inventory-app-1bd22',
    authDomain: 'inventory-app-1bd22.firebaseapp.com',
    storageBucket: 'inventory-app-1bd22.firebasestorage.app',
  );
}
